datasets_dir: /home/zhanglei/projects/Awesome-ReID-for-FCL/datasets/preprocessed-18/
checkpoints_dir: ./ckpts/2022-1-18/
logs_dir: ./logs/2022-1-18/

parallel: 3
device:
  - cuda:0
  - cuda:1

defaults:
  random_seed: 123

  exp_opts:
    comm_rounds: 80
    val_interval: 10
    online_clients: 5

  model_opts:
    name: resnet50
    num_classes: 1000
    last_stride: 1
    neck: bnneck
    fine_tuning:
      - base.layer4
      - gap
      - bottleneck
      - classifier

  criterion_opts:
    name: cross_entropy
    num_classes: 1000
    epsilon: 0.1

  optimizer_opts:
    name: adam
    lr: 1.0e-3
    weight_decay: 1.0e-5

  scheduler_opts:
    name: step_lr
    step_size: 5

  task_opts:
    sustain_rounds: 10
    train_epochs: 5
    augment_opts:
      level: default
      img_size: [ 128,64 ]
      norm_mean: [ 0.485,0.456,0.406 ]
      norm_std: [ 0.229, 0.224, 0.225 ]
    loader_opts:
      batch_size: 64
      num_workers: 4
      pin_memory: true
      persistent_workers: true
      multiprocessing_context: spawn