datasets_dir: ./datasets/preprocessed_shuffle/
checkpoints_dir: ./ckpts/
logs_dir: ./logs/

parallel: 1
device:
  - cuda:0

defaults:
  random_seed: 123

  exp_opts:
    comm_rounds: 60
    val_interval: 10
    online_clients: 5

  model_opts:
    name: resnet18
    num_classes: 8000
    last_stride: 1
    neck: bnneck
    fine_tuning:
      - base.layer4
      - classifier

  criterion_opts:
    name: cross_entropy
    num_classes: 8000
    epsilon: 0.1

  optimizer_opts:
    name: adam
    lr: 1.0e-3
    weight_decay: 1.0e-5

  scheduler_opts:
    name: step_lr
    step_size: 5

  task_opts:
    sustain_rounds: 10
    train_epochs: 5
    augment_opts:
      level: default
      img_size: [ 128,64 ]
      norm_mean: [ 0.485,0.456,0.406 ]
      norm_std: [ 0.229, 0.224, 0.225 ]
    loader_opts:
      batch_size: 64
      num_workers: 0
      pin_memory: false
      persistent_workers: false
      multiprocessing_context: spawn