exp_name: fedstil
exp_method: fedstil

model_opts:
  name: resnet50
  num_classes: 1000
  last_stride: 1
  neck: bnneck
  atten_default: 0.85
  lambda_l1: 1.0e-5
  lambda_kd: 20.0
  fine_tuning:
    - base.layer4
    - gap
    - bottleneck
    - classifier

server:
  server_name: server
  distance_calculate_step: 10
  distance_calculate_decay: 0.8

clients:
  - client_name: client-0
    model_ckpt_name: fedstil_model
    tasks:
      - task-0-0
      - task-0-1
      - task-0-2
      - task-0-3
      - task-0-4
      - task-0-5
      - task-0-6
      - task-0-7

  - client_name: client-1
    model_ckpt_name: fedstil_model
    tasks:
      - task-1-0
      - task-1-1
      - task-1-2
      - task-1-3
      - task-1-4
      - task-1-5
      - task-1-6
      - task-1-7

  - client_name: client-2
    model_ckpt_name: fedstil_model
    tasks:
      - task-2-0
      - task-2-1
      - task-2-2
      - task-2-3
      - task-2-4
      - task-2-5
      - task-2-6
      - task-2-7

  - client_name: client-3
    model_ckpt_name: fedstil_model
    tasks:
      - task-3-0
      - task-3-1
      - task-3-2
      - task-3-3
      - task-3-4
      - task-3-5
      - task-3-6
      - task-3-7

  - client_name: client-4
    model_ckpt_name: fedstil_model
    tasks:
      - task-4-0
      - task-4-1
      - task-4-2
      - task-4-3
      - task-4-4
      - task-4-5
      - task-4-6
      - task-4-7
