exp_name: sm
exp_method: baseline

server:
  server_name: server

clients:
  - client_name: client-0
    model_ckpt_name: sm-model
    tasks:
      - task-0-0
      - task-0-1
      - task-0-2
      - task-0-3
      - task-0-4
      - task-0-5

  - client_name: client-1
    model_ckpt_name: sm-model
    tasks:
      - task-1-0
      - task-1-1
      - task-1-2
      - task-1-3
      - task-1-4
      - task-1-5

  - client_name: client-2
    model_ckpt_name: sm-model
    tasks:
      - task-2-0
      - task-2-1
      - task-2-2
      - task-2-3
      - task-2-4
      - task-2-5

  - client_name: client-3
    model_ckpt_name: sm-model
    tasks:
      - task-3-0
      - task-3-1
      - task-3-2
      - task-3-3
      - task-3-4
      - task-3-5

  - client_name: client-4
    model_ckpt_name: sm-model
    tasks:
      - task-4-0
      - task-4-1
      - task-4-2
      - task-4-3
      - task-4-4
      - task-4-5
