exp_name: icarl
exp_method: icarl

server:
  server_name: server

model_opts:
  name: resnet18
  num_classes: 10
  last_stride: 1
  neck: bnneck
  k: 12000
  n_classes: 10
  examplar_batch_size: 64
  fine_tuning:
    - base.layer4
    - classifier

clients:
  - client_name: client-0
    tasks:
      - task-0-0
      - task-0-1
      - task-0-2
      - task-0-3
      - task-0-4
      - task-0-5

  - client_name: client-1
    tasks:
      - task-1-0
      - task-1-1
      - task-1-2
      - task-1-3
      - task-1-4
      - task-1-5

  - client_name: client-2
    tasks:
      - task-2-0
      - task-2-1
      - task-2-2
      - task-2-3
      - task-2-4
      - task-2-5

  - client_name: client-3
    tasks:
      - task-3-0
      - task-3-1
      - task-3-2
      - task-3-3
      - task-3-4
      - task-3-5

  - client_name: client-4
    tasks:
      - task-4-0
      - task-4-1
      - task-4-2
      - task-4-3
      - task-4-4
      - task-4-5
